controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#api_login_check:
#    path: /api/login_check
#
#api:
#    resource: ../src/Controller/
#    type: attribute
#    prefix: /api